version: "3"

#
services:
  postgresdb:
    image: postgres
    network_mode: bridge
    container_name: postgresdb
    #    volumes:
    #      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
#      - DATABASE_HOST=192.168.1.226
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=murtuza
      - POSTGRES_DB=texashamburger
  #    restart: unless-stopped

  mongodb:
    image: mongo
    network_mode: bridge
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017

  #    restart: unless-stopped

  # APP*****************************************
  texasburgerapp:
    image: texasburger
    network_mode: bridge
    container_name: texasburgerapp
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: always
    depends_on:
      - postgresdb
      - mongodb
#    links:
#      - postgresdb
#      - mongodb

#volumes:
#  postgres-data: